name: Notify Teams
description: Send notification to Microsoft Teams with customizable message
inputs:
  webhook_url:
    description: 'Teams webhook URL'
    required: true
  title:
    description: 'Notification title'
    required: false
    default: 'GitHub Workflow Notification'
  message:
    description: 'Custom message content'
    required: false
    default: ''
  theme_color:
    description: 'Theme color for the card (hex code)'
    required: false
    default: '0076D7'
  status:
    description: 'Workflow status (success/failure)'
    required: false
    default: 'unknown'
runs:
  using: composite
  steps:
    - name: Send Teams Notification
      shell: bash
      run: |
        # Create JSON payload safely using jq to avoid injection
        PAYLOAD=$(jq -n \
          --arg themeColor "${{ inputs.theme_color }}" \
          --arg title "${{ inputs.title }}" \
          --arg message "${{ inputs.message }}" \
          --arg status "${{ inputs.status }}" \
          --arg workflow "${{ github.workflow }}" \
          --arg repository "${{ github.repository }}" \
          --arg refName "${{ github.ref_name }}" \
          --arg sha "${{ github.sha }}" \
          --arg actor "${{ github.actor }}" \
          --arg workflowUrl "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          '{
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "themeColor": $themeColor,
            "summary": $title,
            "sections": [{
              "activityTitle": $title,
              "activitySubtitle": ("Workflow: " + $workflow),
              "text": $message,
              "facts": [
                {
                  "name": "Repository:",
                  "value": $repository
                },
                {
                  "name": "Branch:",
                  "value": $refName
                },
                {
                  "name": "Commit:",
                  "value": $sha
                },
                {
                  "name": "Triggered by:",
                  "value": $actor
                },
                {
                  "name": "Status:",
                  "value": $status
                },
                {
                  "name": "Workflow URL:",
                  "value": ("[View Details](" + $workflowUrl + ")")
                }
              ]
            }]'
        )

        # Send the notification using the safely constructed payload
        curl -H "Content-Type: application/json" \
          -d "$PAYLOAD" \
          "${{ inputs.webhook_url }}"
