name: Docker App Management
description: Start or stop the Docker application with optional container listing
inputs:
  operation:
    description: 'Operation to perform: start or stop'
    required: true
  list-containers:
    description: 'Whether to list containers (true/false)'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: List containers before operation
      if: ${{ inputs.list-containers == 'true' }}
      run: docker ps -a
      shell: bash

    - name: Start Docker application
      if: ${{ inputs.operation == 'start' }}
      run: |
        cd practice-software-testing
        docker-compose up -d --build
      shell: bash

    - name: Stop Docker application
      if: ${{ inputs.operation == 'stop' }}
      run: |
        set -e
        cd practice-software-testing
        docker-compose down -v --remove-orphans
      shell: bash

    - name: List containers after operation
      if: ${{ inputs.list-containers == 'true' }}
      run: docker ps -a
      shell: bash 