name: Setup Node Project
description: Checkout and install dependencies
runs:
  using: composite
  steps:
    - name: Cache node_modules and npm cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      shell: bash
