name: Install NPM Dependencies with Cache
description: Set up npm cache and install project dependencies using npm ci
runs:
  using: "composite"
  steps:
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      shell: bash