name: SonarQube Setup
description: Setup SonarQube scanner and environment for code quality analysis
inputs:
  sonar_token:
    description: 'SonarCloud token for authentication'
    required: true
  sonar_organization:
    description: 'SonarCloud organization name'
    required: true
  project_key:
    description: 'SonarCloud project key'
    required: true
    default: 'toolshop-ui-e2e-playwright-demo'
runs:
  using: composite
  steps:
    - name: Install SonarScanner
      shell: bash
      run: |
        echo "🔧 Installing SonarScanner..."
        brew install sonar-scanner

    - name: Verify SonarScanner installation
      shell: bash
      run: |
        echo "✅ SonarScanner version:"
        sonar-scanner --version

    - name: Setup SonarCloud environment
      shell: bash
      run: |
        echo "🌐 Setting up SonarCloud environment..."
        echo "Project Key: ${{ inputs.project_key }}"
        echo "Organization: ${{ inputs.sonar_organization }}"

    - name: Configure SonarQube properties
      shell: bash
      run: |
        echo "📝 Configuring SonarQube properties..."
        if [ -f "sonar-project.properties" ]; then
          echo "✅ sonar-project.properties found"
        else
          echo "⚠️ sonar-project.properties not found, using default configuration"
        fi
